# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIBotVoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 346)
        MainWindow.setMaximumSize(QtCore.QSize(512, 346))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/voice-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_speak = QtWidgets.QPushButton(self.centralwidget)
        self.btn_speak.setGeometry(QtCore.QRect(10, 280, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btn_speak.setFont(font)
        self.btn_speak.setStyleSheet("QPushButton#btn_speak{\n"
"border-radius: 10px;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 170, 0);\n"
"border-style: solid;\n"
"padding: 1 px 1px 1px 1px;\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(0, 170, 0)\n"
"}\n"
"QPushButton#btn_speak:hover{\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QPushButton#btn_speak:pressed{\n"
"padding-left: 2px;\n"
"padding-top: 2px;\n"
"background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0)\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/micro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_speak.setIcon(icon1)
        self.btn_speak.setIconSize(QtCore.QSize(24, 24))
        self.btn_speak.setObjectName("btn_speak")
        self.btn_input = QtWidgets.QPushButton(self.centralwidget)
        self.btn_input.setGeometry(QtCore.QRect(270, 280, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btn_input.setFont(font)
        self.btn_input.setStyleSheet("QPushButton#btn_input{\n"
"border-radius: 10px;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 170, 0);\n"
"border-style: solid;\n"
"padding: 1 px 1px 1px 1px;\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(0, 170, 0)\n"
"}\n"
"QPushButton#btn_input:hover{\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QPushButton#btn_input:pressed{\n"
"padding-left: 2px;\n"
"padding-top: 2px;\n"
"background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0)\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_input.setIcon(icon2)
        self.btn_input.setIconSize(QtCore.QSize(24, 24))
        self.btn_input.setObjectName("btn_input")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 491, 61))
        self.groupBox_2.setStyleSheet("#groupBox_2 {\n"
"border:2px solid rgb(85, 170, 0);\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_vi = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_vi.sizePolicy().hasHeightForWidth())
        self.cb_vi.setSizePolicy(sizePolicy)
        self.cb_vi.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/vietnam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_vi.setIcon(icon3)
        self.cb_vi.setObjectName("cb_vi")
        self.horizontalLayout.addWidget(self.cb_vi)
        self.cb_en = QtWidgets.QRadioButton(self.groupBox_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/united-kingdom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_en.setIcon(icon4)
        self.cb_en.setObjectName("cb_en")
        self.horizontalLayout.addWidget(self.cb_en)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 60, 151, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/bot.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Juny"))
        self.label.setText(_translate("MainWindow", "Trạng thái ..."))
        self.btn_speak.setText(_translate("MainWindow", "Ấn để nói !"))
        self.btn_input.setText(_translate("MainWindow", "Nhập nội dung !"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Chọn ngôn ngữ"))
        self.cb_vi.setText(_translate("MainWindow", "Tiếng Việt"))
        self.cb_en.setText(_translate("MainWindow", "English"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
